### POST request to create an alarm
POST {{host}}/alarms
Content-Type: application/json

{
  "name": "test",
  "severity": "critical"
}

> {%
  client.test("Create an alarm successfully", function() {
    client.assert(response.status === 201, "Response status is not 201");
  })
%}

### POST request to create an alarm
POST {{host}}/alarms
Content-Type: application/json

{
  "name": "test"
}

> {%
  client.test("Create an alarm successfully", function() {
    client.assert(response.status === 201, "Response status is not 201");
  })
%}
###
